services:
  aggregationservice.api:
    image: ${DOCKER_REGISTRY-}aggregationserviceapi
    build:
      context: .
      dockerfile: AggregationService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServicesOptions__ProductSimulationUrl=http://productsimulation.api:80
      - ServicesOptions__PricingSimulationUrl=http://pricingsimulation.api:80
      - ServicesOptions__StockSimulationUrl=http://stocksimulation.api:80
      - MessagingOptions__HostName=rabbitmq
      - MessagingOptions__Port=5672
      - MessagingOptions__UserName=guest
      - MessagingOptions__Password=guest
      - MessagingOptions__ExchangeName=product-events
      - MessagingOptions__RoutingKey=product.aggregated
    ports:
      - "5001:80"
    depends_on:
      - productsimulation.api
      - pricingsimulation.api
      - stocksimulation.api
      - rabbitmq

  productsimulation.api:
    image: ${DOCKER_REGISTRY-}productsimulationapi
    build:
      context: .
      dockerfile: ProductSimulation.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5003:80"

  pricingsimulation.api:
    image: ${DOCKER_REGISTRY-}pricingsimulationapi
    build:
      context: .
      dockerfile: PricingSimulation.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5005:80"

  stocksimulation.api:
    image: ${DOCKER_REGISTRY-}stocksimulationapi
    build:
      context: .
      dockerfile: StockSimulation.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5007:80"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"