<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AggregationService.Connector\AggregationService.Application.csproj" />
    <ProjectReference Include="..\AggregationService.Domain\AggregationService.Domain.csproj" />
  </ItemGroup>

</Project>
